#!/bin/bash

#altere conforme sua necessidade
#by kuhnen

LOG=/var/log/monitor.log
TELEGRAM_BOT_TOKEN="SEU_TOKEN_AQUI"
CHAT_ID="SEU_CHAT_ID_AQUI"

echo
echo "= $(date +%d/%m/%Y-%kh%Mm) =" >> "$LOG"
snmp_output=$(snmpget -v 2c -c public 192.168.0.22 .1.3.6.1.2.1.1.3.0) #altere o ip, pelo ip do equipamento que vc quer monitorar
echo "RB HOME UPTIME" >> /var/log/monitor.log
echo "$snmp_output" >> "$LOG"

# Enviar para o Telegram
telegram_send_message() {
    local message="$1"
    curl -s -X POST "https://api.telegram.org/botxxxxx:seu_token_aqui/sendMessage" \
        -d "chat_id=$CHAT_ID" \
        -d "text=$message"
}

telegram_send_message "UPTIME_mikrotik: $snmp_output"
